### ISSUE TITLE
Perl Command Seperator ; get lost

### ISSUE THREAD

**Issue by faulhju** [sebbo2002/fhem-cli#10]
In *.cfg file the following attribute command with inline perl commands ; seperated is defined:
`attr SZ.RolladenRechts userReadings pct { my $v = ReadingsVal("SZ.RolladenRechts","state",0);; $v  = substr($v,4, 2);; $v = int($v);; return $v }`

After fhem push the correct attribute will be generated but only with a single ;
`attr SZ.RolladenRechts userReadings pct { my $v = ReadingsVal("SZ.RolladenRechts","state",0); $v  = substr($v,4, 2); $v = int($v); return $v }`

When using fhem pull the former double ;; will be converted to only a single ; .
These command generate "unknown comand" errors when fhem push

**Comment by sebbo2002** [comment]
I was able to reproduce the error. Line breaks apparently didn't work either. With the current version 0.2.0 the following example works for me now:

```
define test dummy
attr test userReadings pct { \
	my $v = ReadingsVal("SZ.RolladenRechts","state",0);; \
	$v = substr($v,4, 2);; \
	$v = int($v);; \
	return $v \
}
```

Please give it a try and close this issue if it works for you as well, thanks ☺️

**Comment by faulhju** [comment]
Works for me :)
